### PR TITLE
Setup linters

### PR DESCRIPTION
**Pull request by Zeph180**
- First, make sure you have [Node.js](https://nodejs.org/en/) installed on your machine
- The easiest way to create a React application is using [Create React App](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app)
- The application should run in the browser without errors

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Zeph180, kindly use the updated microverse [readme ](https://github.com/microverseinc/readme-template) template, all sections from the template should be present in your readme only the  FAQ is optional

**Comment by Zeph180** [comment]
@prolajumokeoni 
:sunglasses:  I thought readme files are only required for the final pull request. 
Thanks for the feedback though.

**Comment by prolajumokeoni** [comment]
> 
@Zeph180 
Using  the updated microverse readme template in your pr is a requirement to get a review

**Comment by prolajumokeoni** [comment]
Hi @Zeph180 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a professional readme, 
Kindly use the updated version  of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Zeph180** [comment]
@prolajumokeoni 
Thanks for the feedback.
:sunglasses: It helped correct something I have been doing wrong since module one. I'm grateful

**Review by Whoistolu — APPROVED** [review]
### Hi @Zeph180 

Great job implementing the recommendations by the previous reviewer upon invalidation 👍🏽 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

### Highlight
🔆 The project setup has the appropriate Create React App Scripts
```json
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
```

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
